version: '3.8'

services:

  app:
    build:
      context: ./blog-api
      dockerfile: Dockerfile
    image: laravel-blog-app
    container_name: laravel-blog-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./blog-api:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    command: sh -c "php artisan migrate  --seed --force && php-fpm"

  nginx:
    image: nginx:alpine
    container_name: laravel-blog-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./blog-api:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-blog-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3307"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
